<?php

// Per-page <head> meta, keyed by route slug. Edit here to tune SEO.
return [
    'meta' => [

        // ---------- Group ----------
        'home' => [
            'title' => 'Evergreen — Solar, Construction & Hardware in Siargao',
            'description' => 'Evergreen is an island group of businesses — Evergreen Solar, Evergreen Frame Construction, and Evergreen Hardware Supply — powering and building homes across Siargao, Philippines.',
            'canonical' => 'https://www.ever-green.ph/',
            'og_title' => 'Evergreen — Siargao\'s solar, construction & hardware group',
            'og_description' => 'Solar systems, steel-frame construction, and building materials — engineered for island living across Siargao.',
            'og_url' => 'https://www.ever-green.ph/',
            'twitter_title' => 'Evergreen — solar, construction & hardware, Siargao',
            'twitter_description' => 'Solar systems, steel-frame construction, and building materials — engineered for island living across Siargao.',
        ],
        'about' => [
            'title' => 'About Evergreen — Solar, Construction & Hardware in Siargao',
            'description' => 'Evergreen — a Siargao group spanning solar power, steel-frame construction, and hardware supply, shaped by over 12 years of powering and building across the island.',
            'canonical' => 'https://www.ever-green.ph/about',
            'og_title' => 'About Evergreen',
            'og_description' => 'One island group, three businesses — solar, construction, and hardware — built on precision, reliability, and results that last.',
            'og_url' => 'https://www.ever-green.ph/about',
            'twitter_title' => 'About Evergreen',
            'twitter_description' => 'One island group, three businesses — solar, construction, and hardware — built on precision, reliability, and results that last.',
        ],
        'contact' => [
            'title' => 'Contact Evergreen — Siargao',
            'description' => 'Contact Evergreen for solar installation, steel-frame construction, and hardware supply across Siargao Island. Our non-public office is in General Luna, Surigao del Norte.',
            'canonical' => 'https://www.ever-green.ph/contact',
            'og_title' => 'Contact Evergreen',
            'og_description' => 'Talk to our Siargao team about solar installation, steel-frame construction, or building materials. Office in General Luna; not open to the public.',
            'og_url' => 'https://www.ever-green.ph/contact',
            'twitter_title' => 'Contact Evergreen',
            'twitter_description' => 'Talk to our Siargao team about solar installation, steel-frame construction, or building materials. Office in General Luna; not open to the public.',
        ],
        'terms' => [
            'title' => 'Terms & Conditions — Evergreen',
            'description' => 'The terms and conditions governing the use of the Evergreen website and our services across Siargao Island.',
            'canonical' => 'https://www.ever-green.ph/terms',
            'og_title' => 'Terms & Conditions — Evergreen',
            'og_description' => 'The terms and conditions governing the use of the Evergreen website and our services across Siargao Island.',
            'og_url' => 'https://www.ever-green.ph/terms',
            'twitter_title' => 'Terms & Conditions — Evergreen',
            'twitter_description' => 'The terms and conditions governing the use of the Evergreen website and our services across Siargao Island.',
        ],
        'privacy' => [
            'title' => 'Privacy Policy — Evergreen',
            'description' => 'How Evergreen collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
            'canonical' => 'https://www.ever-green.ph/privacy',
            'og_title' => 'Privacy Policy — Evergreen',
            'og_description' => 'How Evergreen collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
            'og_url' => 'https://www.ever-green.ph/privacy',
            'twitter_title' => 'Privacy Policy — Evergreen',
            'twitter_description' => 'How Evergreen collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
        ],
        'accessibility' => [
            'title' => 'Accessibility Statement — Evergreen',
            'description' => 'Evergreen\'s commitment to keeping our website usable by everyone, including people with disabilities.',
            'canonical' => 'https://www.ever-green.ph/accessibility',
            'og_title' => 'Accessibility Statement — Evergreen',
            'og_description' => 'Evergreen\'s commitment to keeping our website usable by everyone, including people with disabilities.',
            'og_url' => 'https://www.ever-green.ph/accessibility',
            'twitter_title' => 'Accessibility Statement — Evergreen',
            'twitter_description' => 'Evergreen\'s commitment to keeping our website usable by everyone, including people with disabilities.',
        ],

        // ---------- Evergreen Solar ----------
        'solar' => [
            'title' => 'Evergreen Solar — Solar Installation in Siargao',
            'description' => 'High-performance solar systems engineered for reliability, long-term savings, and dependable energy — built for island living on Siargao. Grid-tied, off-grid, and hybrid installs.',
            'canonical' => 'https://www.ever-green.ph/solar',
            'og_title' => 'Evergreen Solar — Powering Siargao',
            'og_description' => 'Solar systems engineered for island living. Grid-tied, off-grid, and hybrid installs across Siargao Island.',
            'og_url' => 'https://www.ever-green.ph/solar',
            'twitter_title' => 'Evergreen Solar — Powering Siargao',
            'twitter_description' => 'Solar systems engineered for island living. Grid-tied, off-grid, and hybrid installs across Siargao Island.',
        ],
        'solar-services' => [
            'title' => 'Solar Services in Siargao — Evergreen Solar',
            'description' => 'Reliable solar solutions for island living — installation, roofing, battery storage, energy audits, monitoring, consultation, activation, and warranty support across Siargao Island.',
            'canonical' => 'https://www.ever-green.ph/solar/services',
            'og_title' => 'Services — Evergreen Solar',
            'og_description' => 'From energy audit to lifetime support — every step of going solar, engineered for the salt air, sun, and storms of island living.',
            'og_url' => 'https://www.ever-green.ph/solar/services',
            'twitter_title' => 'Services — Evergreen Solar',
            'twitter_description' => 'From energy audit to lifetime support — every step of going solar, engineered for the salt air, sun, and storms of island living.',
        ],
        'solar-packages' => [
            'title' => 'Hybrid Solar Packages & Prices — Evergreen Solar',
            'description' => 'Compare five Evergreen hybrid solar packages, from 3 to 12 kVA. See advertised prices, panels, battery storage, installation inclusions, and warranties.',
            'canonical' => 'https://www.ever-green.ph/solar/packages',
            'og_title' => 'Hybrid Solar Packages — Evergreen Solar',
            'og_description' => 'Compare equipment, battery storage, and advertised prices for five hybrid solar packages. Request a free quote and site assessment.',
            'og_url' => 'https://www.ever-green.ph/solar/packages',
            'twitter_title' => 'Hybrid Solar Packages — Evergreen Solar',
            'twitter_description' => 'Compare equipment, battery storage, and advertised prices for five hybrid solar packages. Request a free quote and site assessment.',
        ],
        'solar-estimate' => [
            'title' => 'Solar Cost & Savings Estimate for Siargao | Evergreen Solar',
            'description' => 'Estimate your solar system size, cost, and savings in 30 seconds. Enter your monthly electricity bill and get an instant, tailored estimate for grid-tied, off-grid, or hybrid solar on Siargao Island.',
            'canonical' => 'https://www.ever-green.ph/solar/estimate',
            'og_title' => 'Solar Cost & Savings Estimate for Siargao — Evergreen Solar',
            'og_description' => 'Enter your monthly electricity bill and instantly size your solar system, cost, and savings — then get a detailed quote from Evergreen Solar.',
            'og_url' => 'https://www.ever-green.ph/solar/estimate',
            'twitter_title' => 'Solar Cost & Savings Estimate for Siargao — Evergreen Solar',
            'twitter_description' => 'Enter your monthly electricity bill and instantly size your solar system, cost, and savings — then get a detailed quote from Evergreen Solar.',
        ],
        'solar-projects' => [
            'title' => 'Solar Projects in Siargao — Evergreen Solar',
            'description' => 'Selected Evergreen Solar installations across Siargao — homestays, villas, and hostels powered by sun.',
            'canonical' => 'https://www.ever-green.ph/solar/projects',
            'og_title' => 'Solar Installations Across Siargao — Evergreen Solar',
            'og_description' => 'We build projects that last. A look at solar installations across Siargao Island.',
            'og_url' => 'https://www.ever-green.ph/solar/projects',
            'twitter_title' => 'Solar Installations Across Siargao — Evergreen Solar',
            'twitter_description' => 'We build projects that last. A look at solar installations across Siargao Island.',
        ],

        // ---------- Evergreen Frame Construction ----------
        'construction' => [
            'title' => 'Evergreen Frame Construction — Steel Framing in Siargao',
            'description' => 'Evergreen Frame Construction — durable light-gauge steel-frame building for homes, resorts, and commercial projects across Siargao. Engineered for the salt air, sun, and storms.',
            'canonical' => 'https://www.ever-green.ph/construction',
            'og_title' => 'Evergreen Frame Construction',
            'og_description' => 'Light-gauge steel-frame construction engineered for island living — fast, durable, termite-proof builds across Siargao.',
            'og_url' => 'https://www.ever-green.ph/construction',
            'twitter_title' => 'Evergreen Frame Construction',
            'twitter_description' => 'Light-gauge steel-frame construction engineered for island living — fast, durable, termite-proof builds across Siargao.',
        ],

        // ---------- Evergreen Hardware Supply ----------
        'hardware' => [
            'title' => 'Building Materials & Hardware Supply in Siargao | Evergreen',
            'description' => 'Evergreen Hardware Supply — building materials for island builds: cement board, marine plywood, phenolic board, rockwool, SPC flooring and more. Burgos warehouse pickup by arrangement.',
            'canonical' => 'https://www.ever-green.ph/hardware',
            'og_title' => 'Building Materials & Hardware Supply in Siargao — Evergreen',
            'og_description' => 'Cement board, marine plywood, phenolic board, rockwool, SPC flooring and more. Current price list and Burgos warehouse pickup by arrangement.',
            'og_url' => 'https://www.ever-green.ph/hardware',
            'twitter_title' => 'Building Materials & Hardware Supply in Siargao — Evergreen',
            'twitter_description' => 'Cement board, marine plywood, phenolic board, rockwool, SPC flooring and more. Current price list and Burgos warehouse pickup by arrangement.',
        ],

    ],
];
