<?php
// Per-page <head> meta. Generated during the Laravel migration; edit here to tune SEO.
return [
    'meta' => [
        'home' => [
            'title' => 'Evergreen Solar — Powering Siargao',
            'description' => 'High-performance solar systems engineered for reliability, long-term savings, and dependable energy — built for island living on Siargao. Grid-tied, off-grid, and hybrid solar installs across Siargao Island.',
            'canonical' => 'https://www.ever-green.ph',
            'og_title' => 'Evergreen Solar — Powering Siargao',
            'og_description' => 'Solar systems engineered for island living. Grid-tied, off-grid, and hybrid installs across the Philippine islands.',
            'og_url' => 'https://www.ever-green.ph',
            'twitter_title' => 'Evergreen Solar — Powering Siargao',
            'twitter_description' => 'Solar systems engineered for island living. Grid-tied, off-grid, and hybrid installs across the Philippine islands.',
        ],
        'services' => [
            'title' => 'Services — Evergreen Solar',
            'description' => 'Reliable solar solutions for island living — installation, roofing, battery storage, energy audits, monitoring, consultation, activation, and warranty support across Siargao Island.',
            'canonical' => 'https://www.ever-green.ph/services',
            'og_title' => 'Services — Evergreen Solar',
            'og_description' => 'From energy audit to lifetime support — every step of going solar, engineered for the salt air, sun, and storms of island living.',
            'og_url' => 'https://www.ever-green.ph/services',
            'twitter_title' => 'Services — Evergreen Solar',
            'twitter_description' => 'From energy audit to lifetime support — every step of going solar, engineered for the salt air, sun, and storms of island living.',
        ],
        'estimate' => [
            'title' => 'Solar Estimate — Evergreen Solar',
            'description' => 'Estimate your solar system size, cost, and savings in 30 seconds. Enter your monthly electricity bill and get an instant, tailored estimate for grid-tied, off-grid, or hybrid solar on Siargao Island.',
            'canonical' => 'https://www.ever-green.ph/estimate',
            'og_title' => 'Solar Estimate — Evergreen Solar',
            'og_description' => 'Enter your monthly electricity bill and instantly size your solar system, cost, and savings — then get a detailed quote from Evergreen Solar.',
            'og_url' => 'https://www.ever-green.ph/estimate',
            'twitter_title' => 'Solar Estimate — Evergreen Solar',
            'twitter_description' => 'Enter your monthly electricity bill and instantly size your solar system, cost, and savings — then get a detailed quote from Evergreen Solar.',
        ],
        'projects' => [
            'title' => 'Projects — Evergreen Solar',
            'description' => 'Selected Evergreen Solar installations across Siargao — homestays, villas, and hostels powered by sun.',
            'canonical' => 'https://www.ever-green.ph/projects',
            'og_title' => 'Projects — Evergreen Solar',
            'og_description' => 'We build projects that last. A look at solar installs across the islands.',
            'og_url' => 'https://www.ever-green.ph/projects',
            'twitter_title' => 'Projects — Evergreen Solar',
            'twitter_description' => 'We build projects that last. A look at solar installs across the islands.',
        ],
        'about' => [
            'title' => 'About — Evergreen Solar',
            'description' => 'Evergreen Solar — premium, high-performance solar for Siargao, shaped by over 12 years of experience powering homes and businesses across the island.',
            'canonical' => 'https://www.ever-green.ph/about',
            'og_title' => 'About — Evergreen Solar',
            'og_description' => 'We build for energy independence — precision, reliability, and results that stand the test of time.',
            'og_url' => 'https://www.ever-green.ph/about',
            'twitter_title' => 'About — Evergreen Solar',
            'twitter_description' => 'We build for energy independence — precision, reliability, and results that stand the test of time.',
        ],
        'terms' => [
            'title' => 'Terms & Conditions — Evergreen Solar',
            'description' => 'The terms and conditions governing the use of the Evergreen Solar website and our solar engineering services across the Philippines.',
            'canonical' => 'https://www.ever-green.ph/terms',
            'og_title' => 'Terms & Conditions — Evergreen Solar',
            'og_description' => 'The terms and conditions governing the use of the Evergreen Solar website and our solar engineering services across the Philippines.',
            'og_url' => 'https://www.ever-green.ph/terms',
            'twitter_title' => 'Terms & Conditions — Evergreen Solar',
            'twitter_description' => 'The terms and conditions governing the use of the Evergreen Solar website and our solar engineering services across the Philippines.',
        ],
        'privacy' => [
            'title' => 'Privacy Policy — Evergreen Solar',
            'description' => 'How Evergreen Solar collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
            'canonical' => 'https://www.ever-green.ph/privacy',
            'og_title' => 'Privacy Policy — Evergreen Solar',
            'og_description' => 'How Evergreen Solar collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
            'og_url' => 'https://www.ever-green.ph/privacy',
            'twitter_title' => 'Privacy Policy — Evergreen Solar',
            'twitter_description' => 'How Evergreen Solar collects, uses, and protects your personal information, in accordance with the Philippine Data Privacy Act.',
        ],
        'accessibility' => [
            'title' => 'Accessibility Statement — Evergreen Solar',
            'description' => 'Evergreen Solar\'s commitment to keeping our website usable by everyone, including people with disabilities.',
            'canonical' => 'https://www.ever-green.ph/accessibility',
            'og_title' => 'Accessibility Statement — Evergreen Solar',
            'og_description' => 'Evergreen Solar\'s commitment to keeping our website usable by everyone, including people with disabilities.',
            'og_url' => 'https://www.ever-green.ph/accessibility',
            'twitter_title' => 'Accessibility Statement — Evergreen Solar',
            'twitter_description' => 'Evergreen Solar\'s commitment to keeping our website usable by everyone, including people with disabilities.',
        ],
        'construction' => [
            'title' => 'Frame Construction — Evergreen',
            'description' => 'Evergreen Frame Construction — light-gauge steel-frame building and quality construction materials for island living across Siargao. Pickup in Burgos.',
            'canonical' => 'https://www.ever-green.ph/construction',
            'og_title' => 'Evergreen Frame Construction',
            'og_description' => 'Steel-frame construction and building materials engineered for the salt air, sun, and storms of island living.',
            'og_url' => 'https://www.ever-green.ph/construction',
            'twitter_title' => 'Evergreen Frame Construction',
            'twitter_description' => 'Steel-frame construction and building materials engineered for the salt air, sun, and storms of island living.',
        ],
        'construction-materials' => [
            'title' => 'Building Materials Price List — Evergreen Frame Construction',
            'description' => 'Current building materials price list from Evergreen Frame Construction — cement board, marine plywood, phenolic board, rockwool, SPC flooring. Pickup in Burgos, Siargao.',
            'canonical' => 'https://www.ever-green.ph/construction/materials',
            'og_title' => 'Building Materials Price List — Evergreen',
            'og_description' => 'Cement board, marine plywood, phenolic board, rockwool, SPC flooring and more. Contact us for project quotes.',
            'og_url' => 'https://www.ever-green.ph/construction/materials',
            'twitter_title' => 'Building Materials Price List — Evergreen',
            'twitter_description' => 'Cement board, marine plywood, phenolic board, rockwool, SPC flooring and more. Contact us for project quotes.',
        ],
    ],
];
